repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'
    hooks:
    -   id: mypy
        additional_dependencies: [pandas-stubs, types-requests, pandera, numpy]
        args: [--strict, --config-file=pyproject.toml]